### ISSUE TITLE
chapter04 array index out of bounds 

### ISSUE THREAD

**Issue by cavapoo2** [cmbaxter/mastering-akka#13]
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:161)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:88)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:79)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[0m[[31merror[0m] [0m(server/*:[31mdockerCommands[0m) java.lang.ArrayIndexOutOfBoundsException: 1[0m
[0m[[31merror[0m] [0mTotal time: 43 s, completed 05-Jun-2017 19:52:56[0m

**Comment by cavapoo2** [comment]
this is just from running the docker-build.sh inside the docker bash shell. im on windows 10.  By the way what is complete and incomplete folders inside chapter 4. i used the complete. I might just start from chapter 1 and start from a bare skeleton. so many files and dependencies in here, not sure where to begin. i do have casandra running in another terminal, noticed that was needed.

**Comment by cavapoo2** [comment]
hang on , i may have answered my own question in https://github.com/PacktPublishing/Mastering-Akka 
will update if this fixes it

**Comment by cavapoo2** [comment]
ah yes that fixed it

**Comment by chandru-jsr** [comment]
Sorry boss, the problem still exist for me.
