### ISSUE TITLE
chapter 04 .ArrayIndexOutOfBoundsException while ./docker-build.sh in windows

### ISSUE THREAD

**Issue by chandru-jsr** [cmbaxter/mastering-akka#16]
Hi,

While running ./docker-build.sh in windows I am getting the below error, 

[0m[[0minfo[0m] [0mPackaging C:\Users\Chandru\Documents\Mastering-Akka\chapter04\bookstore-app-complete\server\target\scala-2.11\chapter4-server-complete_2.11-0.1.0.jar ...[0m
[0m[[0minfo[0m] [0mDone packaging.[0m
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:161)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:88)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:79)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[0m[[31merror[0m] [0m(server/*:[31mdockerCommands[0m) java.lang.ArrayIndexOutOfBoundsException: 1[0m
[0m[[31merror[0m] [0mTotal time: 29 s, completed Sep 5, 2017 8:03:34 PM[0m

Please help me fixing this.

Thanks,
Chandru.

**Comment by chandru-jsr** [comment]
This issue resolved by upgrading to addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.2.0")
